
name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run tests
        run: npx playwright test

      # Upload Playwright test report (HTML)
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()   # upload even if tests fail
        with:
          name: playwright-report
          path: playwright-report
